#!/usr/bin/env bash

# OpenShift project, templates will be changed to this value
openshift_project="topological-inventory-ci"
account_number="6089719" # insights-qa account

# It serves as tenant's authorization. For our purpose, account number can be any value.
# Creates records in "tenants" db tables
# And used as x-rh-identity header for curl requests.
plain_rh_identity="{\"identity\":{\"account_number\":\"${account_number}\",\"user\": {\"is_org_admin\":true}}, \"internal\": {\"org_id\": \"000001\"}}"

# base64 can split output to more lines, forbid it with one of following
# depends on base64 version:
#export X_RH_IDENTITY=$(echo ${plain_rh_identity} | base64)
export X_RH_IDENTITY=$(echo ${plain_rh_identity} | base64 --wrap=0)
# export X_RH_IDENTITY=$(echo ${plain_rh_identity} | base64 --break=0)

# Topological API service
# Create routes in openshift to get these hosts
export TOPOLOGICAL_INVENTORY_API_SERVICE_HOST="http://localhost"
export TOPOLOGICAL_INVENTORY_API_SERVICE_PORT=3001
export BASE_PATH="api/topological-inventory/v3.0"

# Sources API service
# Create routes in openshift to get these hosts
export SOURCES_API_SERVICE_HOST="http://localhost"
export SOURCES_API_SERVICE_PORT=3002
export SOURCES_API_BASE_PATH="api/sources/v2.0"

# Name of SourceType created in Sources DB
source_type_name="amazon"

# Config files (will be mapped as "custom.yml" files)
config_file="openshift/config_maps/custom-mock-config.yml"
data_config_file="openshift/config_maps/custom-mock-data.yml"

# How many Sources/deployments/pods will be created
sources_total=1

